### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-cub3D#1]
- [x] support to wall direction, west east north south 
- [x] parse ".cub" file
- [x]  Error Handling
- [x] support to norminette
- [x] fix wall distortion

**Comment by Shuta-syd** [comment]
- [ ] Allow irregular maps to be output as well.

**Comment by Shuta-syd** [comment]
- [ ] arrow key <- ->

**Comment by Shuta-syd** [comment]
- [ ] map error

**Comment by Shuta-syd** [comment]
DONE
